//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hydrogen.General.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TimeSpanLocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimeSpanLocalizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hydrogen.General.Localization.TimeSpanLocalizationResources", typeof(TimeSpanLocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} پیش.
        /// </summary>
        internal static string Ago {
            get {
                return ResourceManager.GetString("Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} روز.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ساعت.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  و .
        /// </summary>
        internal static string Joiner {
            get {
                return ResourceManager.GetString("Joiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} بعد.
        /// </summary>
        internal static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} دقیقه.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ماه.
        /// </summary>
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک روز.
        /// </summary>
        internal static string OneDay {
            get {
                return ResourceManager.GetString("OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک ساعت.
        /// </summary>
        internal static string OneHour {
            get {
                return ResourceManager.GetString("OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک دقیقه.
        /// </summary>
        internal static string OneMinute {
            get {
                return ResourceManager.GetString("OneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک ماه.
        /// </summary>
        internal static string OneMonth {
            get {
                return ResourceManager.GetString("OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک ثانیه.
        /// </summary>
        internal static string OneSecod {
            get {
                return ResourceManager.GetString("OneSecod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک هفته.
        /// </summary>
        internal static string OneWeek {
            get {
                return ResourceManager.GetString("OneWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک سال.
        /// </summary>
        internal static string OneYear {
            get {
                return ResourceManager.GetString("OneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همان لحظه.
        /// </summary>
        internal static string SameMoment {
            get {
                return ResourceManager.GetString("SameMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ثانیه.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامشخص.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} هفته.
        /// </summary>
        internal static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} سال.
        /// </summary>
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفر.
        /// </summary>
        internal static string ZeroDuration {
            get {
                return ResourceManager.GetString("ZeroDuration", resourceCulture);
            }
        }
    }
}
